@startuml first_sequence

header Sequence diagram

title Second selection of a piece 

actor user

'---------'Check if is not the same colour---------'
user -> FormMatch ++ : Grid_Click(object sender, system.EventArgs e)
FormMatch -> GameController ++ : Selection(int cell)

GameController -> Match ++: ValidSelection(int cell, bool firstClick)

Match -> Board ++: SameColour(int cell, Colour colour)
Board -> Cell ++: IsEmpty()
return false

Board -> Cell ++: Colour
Cell -> Piece ++: Colour
return Black
return Black
return false
return true

'---------Check if turn is valid---------'
GameController -> GameController ++: Turn(int start, int target)
GameController -> Match ++: ValidTurn(int start, int target)

'Check if move is valid
Match -> Board ++: ValidMove(int origin, int target)
Board -> Cell ++: ValidMove(int x1, int y1, int x2, int y2)
Cell -> Piece ++: ValidMove(int x1, int y1, int x2, int y2)
return true
return true

'Check if there are a collision
Board -> Board ++: Collision(int origin, int target)
Board -> Cell ++: HasCollision()
Cell -> Piece ++: CanCollide()
return true
return true
loop for each cell between origin and target
    Board -> Cell ++: isEmpty()
    return true
end
return false
return true

'Check Selfcheck
Match -> Board ++: IsEssentialExposed(Color color)

loop for each cell until it finds a essential piece in the parameters color
    Board -> Cell ++: Colour()
    Cell -> Piece ++: Colour()
    return White
    return White
    Board -> Cell ++: IsEssential()
    return true
end

loop for each cell until it finds a piece that can attack the essential piece
    Board -> Cell ++: Colour()
    Cell -> Piece ++: Colour()
    return Black
    return Black
    Board -> Cell ++: ValidMove(int x1, int y1, int x2, int y2)
    return false
end

return false
return true


'Make the turn (Modals)
GameController -> Match ++: MakeTurn(int origin, int target)
Match -> Board ++: MoveCellTo(int origin, int target)
return
return

'Make the turn (Views)
GameController -> Match ++: Export()
return String
GameController -> FormMatch ++: DrawBoard(string board)
return

GameController -> GameController ++: FiftyTurns()
return false

GameController -> GameController ++: SameBoard()
GameController -> Match ++: History()
return string
return false

'TODO Check
'TODO Checkmate
'TODO Castle
'TODO Promotion

@enduml