@startuml
'https://plantuml.com/salt

salt
scale 1.3
skinparam dpi 200
header darkhappy/chess

{^"FormPromotion"
Yo congrats pick a cool thing

() queen
() bishop
() knight
() rook


[Promote baby]
}
@enduml