@startuml sequence

header Sequence diagram

title When a piece eat an other


FormMatch -> ViewController ++ : Grid_Click()

ViewController -> Chess ++: 
ViewController -> Chess ++: 

Chess -> GameController ++:

GameController -> Match ++:

Match -> Board ++:

Board -> Cell ++:

Cell -> Piece ++:

@enduml