@startuml sequence

header Sequence diagram

title When a piece eat an other


FormMatch -> GameController ++ : Grid_Click()

GameController -> Match ++: Selection()

Match -> Board ++: IsEmpty()
Match <-- Board --: 
Match -> Board ++: GetCell()

Board -> Cell ++: GetColour()
Board <-- Cell --:

Match <-- Board --:

@enduml